name: example_app
description: An example project for the animated_check package
version: 1.2.0
publish_to: none

environment:
  sdk: ">=2.12.0"

dependencies:
  flutter:
    sdk: flutter
  animated_check:
    path: ../

dev_dependencies:

flutter:
  uses-material-design: true
