name: animated_check
description: Animated check is a simple animated checkmark widget. This can be used for showing that an action is complete
version: 1.2.0
homepage: https://github.com/chrisedg87/flutter_animated_check

environment:
  sdk: ">=2.12.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:

flutter:
